### ISSUE TITLE
The tools used to plot phylogentic tree

### ISSUE THREAD

**Issue by xieduo7** [DENV-lineages/lineages-paper#3]
Hi @ViralVerity ,

The phylogenetic tree in your paper is very nice. What tools did you use to plot it? ggtree? 
<img width="943" alt="image" src="https://github.com/DENV-lineages/lineages-paper/assets/35059160/e73b0373-f74d-4ebb-9a38-eeab9ad543e9">

Thank you,

Best,
Duo

**Comment by ViralVerity** [comment]
Thanks! I used baltic (https://github.com/evogytis/baltic) which is based on matplotlib

**Comment by xieduo7** [comment]
Hi @ViralVerity ,

Thanks for your quick reply! It is very helpful!

Best,
Duo
